/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diseño;

import AdministradorGrupos.AdministradorGruposLugar;
import AdministradorGrupos.AdministradorGruposTomeTarjeta;
import AdministradorGrupos.GrupoLugar;
import AdministradorGrupos.GrupoTarjeta;
import AdministradorGrupos.ManejadorCasillasPropiedad;
import AdministradorGrupos.ManejadorTiposTomaTarjeta;
import Casillas.Casilla;
import Juego.Tablero;
import Main.MenuPrincipal;
import PilasYColas.ListaDECircular;
import java.io.Serializable;
import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author joel
 */
public class CrearJuego extends javax.swing.JFrame implements Serializable {

    private MenuPrincipal menu;
    private String nombreJuego;
    private int numeroJugadores;
    private int limiteCasas;
    private int limiteHoteles;
    private int dineroInicialJugador;
    private int dineroPorVuelta;
    private int numeroDados;
    private int numeroFilas;
    private int numeroColumnas;
    private int porcentajeHipoteca;
    private Casilla[][] tablero;
    private ListaDECircular<Casilla> recorrido;
    private AdministradorGruposLugar administradorGruposLugar;
    private AdministradorGruposTomeTarjeta administradorGruposTomeTarjeta;
    private ManejadorCasillasPropiedad manejadorCasillasPropiedad;
    private ManejadorTiposTomaTarjeta manejadorTiposTomaTarjeta;
    private Icon warningIcon = new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MonopolyConfundido.png"));

    public CrearJuego(MenuPrincipal menu) {
        this.menu = menu;
        initComponents();
        this.setLocationRelativeTo(null);
        ingresarInfojPanel.setVisible(true);
        //modificarTablerojPanel.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingresarInfojPanel = new javax.swing.JPanel();
        textoPorcentajeHipotecajLabel = new javax.swing.JLabel();
        textoIngreseNombrejLabel = new javax.swing.JLabel();
        nombreJuegojTextField = new javax.swing.JTextField();
        textoCantidadJugadoresjLabel = new javax.swing.JLabel();
        textoDineroInicialjLabel = new javax.swing.JLabel();
        porcentajeHipotecajSpinner = new javax.swing.JSpinner();
        textoLimiteCasasjLabel = new javax.swing.JLabel();
        dineroInicialjSpinner = new javax.swing.JSpinner();
        dineroPorVueltajSpinner = new javax.swing.JSpinner();
        textoLimiteHotelesjLabel = new javax.swing.JLabel();
        textoDineroPorVueltajLabel = new javax.swing.JLabel();
        textoNumeroDadosjLabel = new javax.swing.JLabel();
        limiteCasasjSpinner = new javax.swing.JSpinner();
        noJugadoresjComboBox = new javax.swing.JComboBox<>();
        noDadosjComboBox = new javax.swing.JComboBox<>();
        crearTablerojButton = new javax.swing.JButton();
        savejButton = new javax.swing.JButton();
        regresarMenuPrincipaljButton = new javax.swing.JButton();
        noColumnasjSpinner = new javax.swing.JSpinner();
        textoNumeroFilasjLabel = new javax.swing.JLabel();
        noFilasjSpinner = new javax.swing.JSpinner();
        textoNumeroColumnasjLabel1 = new javax.swing.JLabel();
        limiteHotelesjSpinner = new javax.swing.JSpinner();
        monopolyGuyjLabel = new javax.swing.JLabel();
        textoSimboloPorcentajejLabel = new javax.swing.JLabel();
        jLabelFondoCrearJuego = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingresarInfojPanel.setBackground(new java.awt.Color(31, 67, 92));
        ingresarInfojPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoPorcentajeHipotecajLabel.setBackground(new java.awt.Color(255, 255, 255));
        textoPorcentajeHipotecajLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        textoPorcentajeHipotecajLabel.setForeground(new java.awt.Color(171, 235, 219));
        textoPorcentajeHipotecajLabel.setText("Porcentaje de Hipoteca");
        textoPorcentajeHipotecajLabel.setBorder(new javax.swing.border.MatteBorder(null));
        ingresarInfojPanel.add(textoPorcentajeHipotecajLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 280, 40));

        textoIngreseNombrejLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        textoIngreseNombrejLabel.setForeground(new java.awt.Color(171, 235, 219));
        textoIngreseNombrejLabel.setText("Ingrese el Nombre del Juego:");
        textoIngreseNombrejLabel.setBorder(new javax.swing.border.MatteBorder(null));
        ingresarInfojPanel.add(textoIngreseNombrejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 360, 40));

        nombreJuegojTextField.setBackground(new java.awt.Color(255, 255, 211));
        nombreJuegojTextField.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        nombreJuegojTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreJuegojTextFieldActionPerformed(evt);
            }
        });
        nombreJuegojTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreJuegojTextFieldKeyTyped(evt);
            }
        });
        ingresarInfojPanel.add(nombreJuegojTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 480, 40));

        textoCantidadJugadoresjLabel.setBackground(new java.awt.Color(255, 255, 255));
        textoCantidadJugadoresjLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        textoCantidadJugadoresjLabel.setForeground(new java.awt.Color(171, 235, 219));
        textoCantidadJugadoresjLabel.setText("Cantidad de Jugadores (1-6)");
        textoCantidadJugadoresjLabel.setBorder(new javax.swing.border.MatteBorder(null));
        ingresarInfojPanel.add(textoCantidadJugadoresjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 360, 40));

        textoDineroInicialjLabel.setBackground(new java.awt.Color(255, 255, 255));
        textoDineroInicialjLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        textoDineroInicialjLabel.setForeground(new java.awt.Color(171, 235, 219));
        textoDineroInicialjLabel.setText("Dinero Inicial (Por Jugador)");
        textoDineroInicialjLabel.setBorder(new javax.swing.border.MatteBorder(null));
        ingresarInfojPanel.add(textoDineroInicialjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 360, 40));

        porcentajeHipotecajSpinner.setFont(new java.awt.Font("Capture it", 1, 24)); // NOI18N
        porcentajeHipotecajSpinner.setModel(new javax.swing.SpinnerNumberModel(10, 1, 100, 1));
        ingresarInfojPanel.add(porcentajeHipotecajSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 100, 40));

        textoLimiteCasasjLabel.setBackground(new java.awt.Color(255, 255, 255));
        textoLimiteCasasjLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        textoLimiteCasasjLabel.setForeground(new java.awt.Color(171, 235, 219));
        textoLimiteCasasjLabel.setText("Limite de Casas");
        textoLimiteCasasjLabel.setBorder(new javax.swing.border.MatteBorder(null));
        ingresarInfojPanel.add(textoLimiteCasasjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 190, 40));

        dineroInicialjSpinner.setFont(new java.awt.Font("Capture it", 1, 24)); // NOI18N
        dineroInicialjSpinner.setModel(new javax.swing.SpinnerNumberModel(1500, 1, null, 100));
        ingresarInfojPanel.add(dineroInicialjSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 100, 40));

        dineroPorVueltajSpinner.setFont(new java.awt.Font("Capture it", 1, 24)); // NOI18N
        dineroPorVueltajSpinner.setModel(new javax.swing.SpinnerNumberModel(200, 1, null, 25));
        ingresarInfojPanel.add(dineroPorVueltajSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 100, 40));

        textoLimiteHotelesjLabel.setBackground(new java.awt.Color(255, 255, 255));
        textoLimiteHotelesjLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        textoLimiteHotelesjLabel.setForeground(new java.awt.Color(171, 235, 219));
        textoLimiteHotelesjLabel.setText("Limite de Hoteles");
        textoLimiteHotelesjLabel.setBorder(new javax.swing.border.MatteBorder(null));
        ingresarInfojPanel.add(textoLimiteHotelesjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 220, 40));

        textoDineroPorVueltajLabel.setBackground(new java.awt.Color(255, 255, 255));
        textoDineroPorVueltajLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        textoDineroPorVueltajLabel.setForeground(new java.awt.Color(171, 235, 219));
        textoDineroPorVueltajLabel.setText("Dinero por Vuelta");
        textoDineroPorVueltajLabel.setBorder(new javax.swing.border.MatteBorder(null));
        ingresarInfojPanel.add(textoDineroPorVueltajLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 220, 40));

        textoNumeroDadosjLabel.setBackground(new java.awt.Color(255, 255, 255));
        textoNumeroDadosjLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        textoNumeroDadosjLabel.setForeground(new java.awt.Color(171, 235, 219));
        textoNumeroDadosjLabel.setText("Numero de Dados");
        textoNumeroDadosjLabel.setBorder(new javax.swing.border.MatteBorder(null));
        ingresarInfojPanel.add(textoNumeroDadosjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 220, 40));

        limiteCasasjSpinner.setFont(new java.awt.Font("Capture it", 1, 24)); // NOI18N
        limiteCasasjSpinner.setModel(new javax.swing.SpinnerNumberModel(25, 1, null, 1));
        ingresarInfojPanel.add(limiteCasasjSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 100, 40));

        noJugadoresjComboBox.setFont(new java.awt.Font("Capture it", 1, 24)); // NOI18N
        noJugadoresjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        ingresarInfojPanel.add(noJugadoresjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 100, 40));

        noDadosjComboBox.setFont(new java.awt.Font("Capture it", 1, 24)); // NOI18N
        noDadosjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        noDadosjComboBox.setSelectedIndex(1);
        ingresarInfojPanel.add(noDadosjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 100, 40));

        crearTablerojButton.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        crearTablerojButton.setText("Crear Tablero");
        crearTablerojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearTablerojButtonActionPerformed(evt);
            }
        });
        ingresarInfojPanel.add(crearTablerojButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 380, 70));

        savejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        savejButton.setToolTipText("Guardar");
        savejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButtonActionPerformed(evt);
            }
        });
        ingresarInfojPanel.add(savejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 120, 110));

        regresarMenuPrincipaljButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver.png"))); // NOI18N
        regresarMenuPrincipaljButton.setToolTipText("Retornar al Menu Principal");
        regresarMenuPrincipaljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarMenuPrincipaljButtonActionPerformed(evt);
            }
        });
        ingresarInfojPanel.add(regresarMenuPrincipaljButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 110, 110));

        noColumnasjSpinner.setFont(new java.awt.Font("Capture it", 1, 24)); // NOI18N
        noColumnasjSpinner.setModel(new javax.swing.SpinnerNumberModel(2, 2, 25, 1));
        ingresarInfojPanel.add(noColumnasjSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 280, 100, 40));

        textoNumeroFilasjLabel.setBackground(new java.awt.Color(255, 255, 255));
        textoNumeroFilasjLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        textoNumeroFilasjLabel.setForeground(new java.awt.Color(171, 235, 219));
        textoNumeroFilasjLabel.setText("Numero de Filas");
        textoNumeroFilasjLabel.setBorder(new javax.swing.border.MatteBorder(null));
        ingresarInfojPanel.add(textoNumeroFilasjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 200, 40));

        noFilasjSpinner.setFont(new java.awt.Font("Capture it", 1, 24)); // NOI18N
        noFilasjSpinner.setModel(new javax.swing.SpinnerNumberModel(2, 2, 25, 1));
        ingresarInfojPanel.add(noFilasjSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, 100, 40));

        textoNumeroColumnasjLabel1.setBackground(new java.awt.Color(255, 255, 255));
        textoNumeroColumnasjLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        textoNumeroColumnasjLabel1.setForeground(new java.awt.Color(171, 235, 219));
        textoNumeroColumnasjLabel1.setText("Numero de Columnas");
        textoNumeroColumnasjLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        ingresarInfojPanel.add(textoNumeroColumnasjLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 250, 40));

        limiteHotelesjSpinner.setFont(new java.awt.Font("Capture it", 1, 24)); // NOI18N
        limiteHotelesjSpinner.setModel(new javax.swing.SpinnerNumberModel(15, 1, null, 1));
        ingresarInfojPanel.add(limiteHotelesjSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 100, 40));

        monopolyGuyjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/monopoly-rich-uncle-pennybags.jpg"))); // NOI18N
        ingresarInfojPanel.add(monopolyGuyjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 420, 160));

        textoSimboloPorcentajejLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        textoSimboloPorcentajejLabel.setText("%");
        ingresarInfojPanel.add(textoSimboloPorcentajejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 220, 40, 40));

        getContentPane().add(ingresarInfojPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 900, 610));
        //jPanelIngresarInfo.setOpaque(false);

        jLabelFondoCrearJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CrearMapa (1).jpg"))); // NOI18N
        getContentPane().add(jLabelFondoCrearJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreJuegojTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreJuegojTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreJuegojTextFieldActionPerformed

    private void regresarMenuPrincipaljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarMenuPrincipaljButtonActionPerformed
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresarMenuPrincipaljButtonActionPerformed

    private void savejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButtonActionPerformed
    

    Tablero nuevoTablero = new Tablero(numeroFilas, numeroColumnas, porcentajeHipoteca, tablero, recorrido,
            nombreJuego, numeroJugadores, limiteCasas, limiteHoteles, dineroInicialJugador, dineroPorVuelta, numeroDados,
            administradorGruposLugar, administradorGruposTomeTarjeta, manejadorCasillasPropiedad, manejadorTiposTomaTarjeta);



    }//GEN-LAST:event_savejButtonActionPerformed


    private void crearTablerojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearTablerojButtonActionPerformed
        if (nombreJuegojTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese todos los campos requeridos",
                    "ALERTA", JOptionPane.INFORMATION_MESSAGE, warningIcon);
        } else {

            numeroFilas = (Integer) noFilasjSpinner.getValue();
            numeroColumnas = (Integer) noColumnasjSpinner.getValue();
            porcentajeHipoteca = (Integer) (porcentajeHipotecajSpinner.getValue());
            nombreJuego = nombreJuegojTextField.getText().trim(); //Capturar el nombre y eliminar espacios en blanco sobrantes
            numeroJugadores = Integer.parseInt(noJugadoresjComboBox.getSelectedItem().toString());
            limiteCasas = (Integer) limiteCasasjSpinner.getValue();
            limiteHoteles = (Integer) limiteHotelesjSpinner.getValue();
            dineroInicialJugador = (Integer) dineroInicialjSpinner.getValue();
            dineroPorVuelta = (Integer) dineroPorVueltajSpinner.getValue();
            numeroDados = Integer.parseInt(noDadosjComboBox.getSelectedItem().toString());

            CrearTablero crear = new CrearTablero(numeroColumnas, numeroFilas, porcentajeHipoteca, this);
            crear.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_crearTablerojButtonActionPerformed

    private void nombreJuegojTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreJuegojTextFieldKeyTyped
        validarSoloLetras(evt);
    }//GEN-LAST:event_nombreJuegojTextFieldKeyTyped

    public void validarSoloLetras(java.awt.event.KeyEvent evt) {
        char validar = evt.getKeyChar();

        if ((validar < 'a' || validar > 'z') && (validar < 'A' || validar > 'Z') && validar!=' ') {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se admiten letras",
                    "ALERTA", JOptionPane.INFORMATION_MESSAGE, warningIcon);

        }
    }

    public void deshabilitarComponentes() {
        porcentajeHipotecajSpinner.setEnabled(false);
        noJugadoresjComboBox.setEnabled(false);
        limiteCasasjSpinner.setEnabled(false);
        limiteHotelesjSpinner.setEnabled(false);
        dineroInicialjSpinner.setEnabled(false);
        dineroPorVueltajSpinner.setEnabled(false);
        noDadosjComboBox.setEnabled(false);
        noFilasjSpinner.setEnabled(false);
        noColumnasjSpinner.setEnabled(false);
        regresarMenuPrincipaljButton.setEnabled(false);
        crearTablerojButton.setEnabled(false);
    }
    
    public void transferirDatosTablero(ManejadorCasillasPropiedad manejadorCasillasPropiedad, ManejadorTiposTomaTarjeta manejadorTiposTomaTarjeta,
            AdministradorGruposLugar adminGruposLugar, AdministradorGruposTomeTarjeta adminGruposTarjeta, Casilla[][] tablero,
            ListaDECircular<Casilla> recorrido){
        this.manejadorCasillasPropiedad = manejadorCasillasPropiedad;
        this.manejadorTiposTomaTarjeta = manejadorTiposTomaTarjeta;
        this.administradorGruposLugar = adminGruposLugar;
        this.administradorGruposTomeTarjeta = adminGruposTarjeta;
        this.tablero = tablero;
        this.recorrido = recorrido;
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearTablerojButton;
    private javax.swing.JSpinner dineroInicialjSpinner;
    private javax.swing.JSpinner dineroPorVueltajSpinner;
    private javax.swing.JPanel ingresarInfojPanel;
    private javax.swing.JLabel jLabelFondoCrearJuego;
    private javax.swing.JSpinner limiteCasasjSpinner;
    private javax.swing.JSpinner limiteHotelesjSpinner;
    private javax.swing.JLabel monopolyGuyjLabel;
    private javax.swing.JSpinner noColumnasjSpinner;
    private javax.swing.JComboBox<String> noDadosjComboBox;
    private javax.swing.JSpinner noFilasjSpinner;
    private javax.swing.JComboBox<String> noJugadoresjComboBox;
    private javax.swing.JTextField nombreJuegojTextField;
    private javax.swing.JSpinner porcentajeHipotecajSpinner;
    private javax.swing.JButton regresarMenuPrincipaljButton;
    private javax.swing.JButton savejButton;
    private javax.swing.JLabel textoCantidadJugadoresjLabel;
    private javax.swing.JLabel textoDineroInicialjLabel;
    private javax.swing.JLabel textoDineroPorVueltajLabel;
    private javax.swing.JLabel textoIngreseNombrejLabel;
    private javax.swing.JLabel textoLimiteCasasjLabel;
    private javax.swing.JLabel textoLimiteHotelesjLabel;
    private javax.swing.JLabel textoNumeroColumnasjLabel1;
    private javax.swing.JLabel textoNumeroDadosjLabel;
    private javax.swing.JLabel textoNumeroFilasjLabel;
    private javax.swing.JLabel textoPorcentajeHipotecajLabel;
    private javax.swing.JLabel textoSimboloPorcentajejLabel;
    // End of variables declaration//GEN-END:variables
}
