/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diseño;

import AdministradorGrupos.*;
import Casillas.Lugar;
import java.awt.Color;

/**
 *
 * @author joel
 */
public class InstanciaLugar extends javax.swing.JDialog {

    private CrearTablero crearTablero;
    private ManejadorPropiedades manejadorPropiedades;
    private String[] gruposPropiedades;
    private Color[] coloresGrupo;
    private GrupoLugar[] grupoL;
    private Lugar lugar;
    private Color color;
    private int fila;
    private int columna;
    private int porcentajeHipoteca;
    

    public InstanciaLugar(CrearTablero crearTablero, boolean modal, ManejadorPropiedades manejador,
            int fila, int columna, int porcentajeHipoteca) {
        super(crearTablero, modal);   
        initComponents();
        this.crearTablero = crearTablero;
        manejadorPropiedades = manejador;
        this.fila = fila;
        this.columna = columna;
        this.porcentajeHipoteca = porcentajeHipoteca;
        establecer();
           
    }
    
    public void establecer(){

        gruposPropiedades = manejadorPropiedades.getNombreGrupo();
        coloresGrupo = manejadorPropiedades.getColoresGrupo();
        
        grupoLugarjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(gruposPropiedades));
        colorActualjPanel.setBackground(coloresGrupo[grupoLugarjComboBox.getSelectedIndex()]);
        grupoL = manejadorPropiedades.getGrupoLugar();
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoPropiedadesjLabel = new javax.swing.JLabel();
        textoPrecioPorServiciojLabel2 = new javax.swing.JLabel();
        aumentoPorHoteljSpinner = new javax.swing.JSpinner();
        grupoLugarjComboBox = new javax.swing.JComboBox<>();
        ingresarNombreLugarjTextField = new javax.swing.JTextField();
        aceptarjButton = new javax.swing.JButton();
        textoPrecioComprajLabel = new javax.swing.JLabel();
        textoPrecioPorServiciojLabel4 = new javax.swing.JLabel();
        textoPrecioPorServiciojLabel5 = new javax.swing.JLabel();
        textoPrecioPorServiciojLabel6 = new javax.swing.JLabel();
        textoPrecioPorServiciojLabel7 = new javax.swing.JLabel();
        textoPrecioPorServiciojLabel8 = new javax.swing.JLabel();
        precioComprajSpinner = new javax.swing.JSpinner();
        precioPorHoteljSpinner = new javax.swing.JSpinner();
        precioPorCasajSpinner = new javax.swing.JSpinner();
        aumentoPorCasajSpinner = new javax.swing.JSpinner();
        textoCostoPorEstanciajLabel = new javax.swing.JLabel();
        costoEstanciaSpinner = new javax.swing.JSpinner();
        colorActualjPanel = new javax.swing.JPanel();
        fondoInfoCasillasjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusable(false);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(890, 630));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoPropiedadesjLabel.setBackground(new java.awt.Color(204, 204, 255));
        textoPropiedadesjLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        textoPropiedadesjLabel.setForeground(new java.awt.Color(0, 0, 0));
        textoPropiedadesjLabel.setText("Atributos de Lugar");
        getContentPane().add(textoPropiedadesjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 340, 60));

        textoPrecioPorServiciojLabel2.setBackground(new java.awt.Color(255, 255, 255));
        textoPrecioPorServiciojLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        textoPrecioPorServiciojLabel2.setForeground(new java.awt.Color(198, 38, 38));
        textoPrecioPorServiciojLabel2.setText("Precio por Casa");
        textoPrecioPorServiciojLabel2.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(textoPrecioPorServiciojLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 190, 40));

        aumentoPorHoteljSpinner.setFont(new java.awt.Font("Capture it", 1, 24)); // NOI18N
        aumentoPorHoteljSpinner.setModel(new javax.swing.SpinnerNumberModel(60, 1, null, 10));
        getContentPane().add(aumentoPorHoteljSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 100, 40));

        grupoLugarjComboBox.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        grupoLugarjComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                grupoLugarjComboBoxItemStateChanged(evt);
            }
        });
        grupoLugarjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupoLugarjComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(grupoLugarjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 290, 40));

        ingresarNombreLugarjTextField.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        ingresarNombreLugarjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarNombreLugarjTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(ingresarNombreLugarjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 210, 50));

        aceptarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/complete.png"))); // NOI18N
        aceptarjButton.setContentAreaFilled(false);
        aceptarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarjButtonActionPerformed(evt);
            }
        });
        getContentPane().add(aceptarjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 110, 110));

        textoPrecioComprajLabel.setBackground(new java.awt.Color(255, 255, 255));
        textoPrecioComprajLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        textoPrecioComprajLabel.setForeground(new java.awt.Color(198, 38, 38));
        textoPrecioComprajLabel.setText("Precio Compra");
        textoPrecioComprajLabel.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(textoPrecioComprajLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 180, 40));

        textoPrecioPorServiciojLabel4.setBackground(new java.awt.Color(255, 255, 255));
        textoPrecioPorServiciojLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        textoPrecioPorServiciojLabel4.setForeground(new java.awt.Color(198, 38, 38));
        textoPrecioPorServiciojLabel4.setText("Precio por Hotel");
        textoPrecioPorServiciojLabel4.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(textoPrecioPorServiciojLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 200, 40));

        textoPrecioPorServiciojLabel5.setBackground(new java.awt.Color(255, 255, 255));
        textoPrecioPorServiciojLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        textoPrecioPorServiciojLabel5.setForeground(new java.awt.Color(198, 38, 38));
        textoPrecioPorServiciojLabel5.setText("Elegir Grupo");
        textoPrecioPorServiciojLabel5.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(textoPrecioPorServiciojLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, 40));

        textoPrecioPorServiciojLabel6.setBackground(new java.awt.Color(255, 255, 255));
        textoPrecioPorServiciojLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        textoPrecioPorServiciojLabel6.setForeground(new java.awt.Color(198, 38, 38));
        textoPrecioPorServiciojLabel6.setText("Aumento Estancia por Casa");
        textoPrecioPorServiciojLabel6.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(textoPrecioPorServiciojLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 330, 40));

        textoPrecioPorServiciojLabel7.setBackground(new java.awt.Color(255, 255, 255));
        textoPrecioPorServiciojLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        textoPrecioPorServiciojLabel7.setForeground(new java.awt.Color(198, 38, 38));
        textoPrecioPorServiciojLabel7.setText("Aumento Estancia por Hotel");
        textoPrecioPorServiciojLabel7.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(textoPrecioPorServiciojLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 330, 40));

        textoPrecioPorServiciojLabel8.setBackground(new java.awt.Color(255, 255, 255));
        textoPrecioPorServiciojLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        textoPrecioPorServiciojLabel8.setForeground(new java.awt.Color(198, 38, 38));
        textoPrecioPorServiciojLabel8.setText("Nombre de Lugar");
        textoPrecioPorServiciojLabel8.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(textoPrecioPorServiciojLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 210, 40));

        precioComprajSpinner.setFont(new java.awt.Font("Capture it", 1, 24)); // NOI18N
        precioComprajSpinner.setModel(new javax.swing.SpinnerNumberModel(150, 1, null, 25));
        getContentPane().add(precioComprajSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 100, 40));

        precioPorHoteljSpinner.setFont(new java.awt.Font("Capture it", 1, 24)); // NOI18N
        precioPorHoteljSpinner.setModel(new javax.swing.SpinnerNumberModel(100, 1, null, 20));
        getContentPane().add(precioPorHoteljSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 100, 40));

        precioPorCasajSpinner.setFont(new java.awt.Font("Capture it", 1, 24)); // NOI18N
        precioPorCasajSpinner.setModel(new javax.swing.SpinnerNumberModel(100, 1, null, 20));
        getContentPane().add(precioPorCasajSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 100, 40));

        aumentoPorCasajSpinner.setFont(new java.awt.Font("Capture it", 1, 24)); // NOI18N
        aumentoPorCasajSpinner.setModel(new javax.swing.SpinnerNumberModel(50, 1, null, 10));
        getContentPane().add(aumentoPorCasajSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 100, 40));

        textoCostoPorEstanciajLabel.setBackground(new java.awt.Color(255, 255, 255));
        textoCostoPorEstanciajLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        textoCostoPorEstanciajLabel.setForeground(new java.awt.Color(198, 38, 38));
        textoCostoPorEstanciajLabel.setText("Costo por Estancia");
        textoCostoPorEstanciajLabel.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(textoCostoPorEstanciajLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 230, 40));

        costoEstanciaSpinner.setFont(new java.awt.Font("Capture it", 1, 24)); // NOI18N
        costoEstanciaSpinner.setModel(new javax.swing.SpinnerNumberModel(15, 1, null, 10));
        getContentPane().add(costoEstanciaSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, 100, 40));
        getContentPane().add(colorActualjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 290, 40));

        fondoInfoCasillasjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MonopolyCavalgando.jpg"))); // NOI18N
        fondoInfoCasillasjLabel.setRequestFocusEnabled(false);
        getContentPane().add(fondoInfoCasillasjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarjButtonActionPerformed
        if (ingresarNombreLugarjTextField.getText().isEmpty() || colorActualjPanel.getBackground()==null) {
            crearTablero.mensajeError("Por favor ingrese todos los campos requeridos");
        }
        
        else{
            String nombreLugar = ingresarNombreLugarjTextField.getText().trim();          
            GrupoLugar grupoLugar = grupoL[grupoLugarjComboBox.getSelectedIndex()];
            int precioPorCasa = (Integer)precioPorCasajSpinner.getValue();
            int precioPorHotel = (Integer)precioPorHoteljSpinner.getValue();
            int aumentoPorCasa = (Integer)aumentoPorCasajSpinner.getValue();
            int aumentoPorHotel = (Integer)aumentoPorHoteljSpinner.getValue();
            int precioCompra = (Integer)precioComprajSpinner.getValue();
            int costoEstancia = (Integer)costoEstanciaSpinner.getValue();
            
            Lugar nuevoLugar = new Lugar(grupoLugar, costoEstancia, precioPorCasa, precioPorHotel, aumentoPorCasa, aumentoPorHotel,
            fila, columna, nombreLugar, precioCompra, porcentajeHipoteca);
            Color colorGrupo = colorActualjPanel.getBackground();
            setLugar(nuevoLugar);
            setColor(colorGrupo);
            
            this.setVisible(false);
        }
    }//GEN-LAST:event_aceptarjButtonActionPerformed

    public Lugar getLugar() {
        return lugar;
    }

    public void setLugar(Lugar lugar) {
        this.lugar = lugar;
    }

    public Color getColor() {
        return color;
    }

    public void setColor(Color color) {
        this.color = color;
    }
    
    private void grupoLugarjComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_grupoLugarjComboBoxItemStateChanged
        colorActualjPanel.setBackground(coloresGrupo[grupoLugarjComboBox.getSelectedIndex()]);
    }//GEN-LAST:event_grupoLugarjComboBoxItemStateChanged

    private void ingresarNombreLugarjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarNombreLugarjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarNombreLugarjTextFieldActionPerformed

    private void grupoLugarjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupoLugarjComboBoxActionPerformed
        
    }//GEN-LAST:event_grupoLugarjComboBoxActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarjButton;
    private javax.swing.JSpinner aumentoPorCasajSpinner;
    private javax.swing.JSpinner aumentoPorHoteljSpinner;
    private javax.swing.JPanel colorActualjPanel;
    private javax.swing.JSpinner costoEstanciaSpinner;
    private javax.swing.JLabel fondoInfoCasillasjLabel;
    private javax.swing.JComboBox<String> grupoLugarjComboBox;
    private javax.swing.JTextField ingresarNombreLugarjTextField;
    private javax.swing.JSpinner precioComprajSpinner;
    private javax.swing.JSpinner precioPorCasajSpinner;
    private javax.swing.JSpinner precioPorHoteljSpinner;
    private javax.swing.JLabel textoCostoPorEstanciajLabel;
    private javax.swing.JLabel textoPrecioComprajLabel;
    private javax.swing.JLabel textoPrecioPorServiciojLabel2;
    private javax.swing.JLabel textoPrecioPorServiciojLabel4;
    private javax.swing.JLabel textoPrecioPorServiciojLabel5;
    private javax.swing.JLabel textoPrecioPorServiciojLabel6;
    private javax.swing.JLabel textoPrecioPorServiciojLabel7;
    private javax.swing.JLabel textoPrecioPorServiciojLabel8;
    private javax.swing.JLabel textoPropiedadesjLabel;
    // End of variables declaration//GEN-END:variables
}
