/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diseño;

import Casillas.Estacion;
import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author joel
 */
public class InstanciarEstacion extends javax.swing.JDialog {

    private CrearTablero crearTablero;
    private int fila;
    private int columna;
    private int porcentajeHipoteca;
    private int costoPorEstacion;
    private int usoEstacion;
    private Color colorEstacion = null;
    private Estacion estacion;

    /**
     * Creates new form InstanciarEstacion
     * @param crearTablero
     * @param modal
     */
    public InstanciarEstacion(CrearTablero crearTablero, boolean modal, int fila, int columna,
            int porcentajeHipoteca, int costoPorEstacion, int usoEstacion) {
        super(crearTablero, modal);
        initComponents();
        this.crearTablero = crearTablero;
        this.fila = fila;
        this.columna = columna;
        this.porcentajeHipoteca = porcentajeHipoteca;
        this.costoPorEstacion = costoPorEstacion;
        this.usoEstacion = usoEstacion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoPropiedadesEstacionjLabel = new javax.swing.JLabel();
        nombreEstacionjTextField = new javax.swing.JTextField();
        panelContTextColorEstacionjPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelContTextNombrejPanel = new javax.swing.JPanel();
        textoNombreEstacionjLabel = new javax.swing.JLabel();
        checkjButton = new javax.swing.JButton();
        pickColorjButton = new javax.swing.JButton();
        colorActualjPanel = new javax.swing.JPanel();
        fondoPropEstacionjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusable(false);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(785, 415));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoPropiedadesEstacionjLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        textoPropiedadesEstacionjLabel.setForeground(new java.awt.Color(0, 0, 0));
        textoPropiedadesEstacionjLabel.setText("Propiedades Estacion");
        getContentPane().add(textoPropiedadesEstacionjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 500, 70));

        nombreEstacionjTextField.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        getContentPane().add(nombreEstacionjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 290, 60));

        panelContTextColorEstacionjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(221, 221, 221));
        jLabel1.setText("Color de Estacion");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelContTextColorEstacionjPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 60));

        getContentPane().add(panelContTextColorEstacionjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 340, 80));

        textoNombreEstacionjLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        textoNombreEstacionjLabel.setForeground(new java.awt.Color(221, 221, 221));
        textoNombreEstacionjLabel.setText("Nombre de Estacion");
        textoNombreEstacionjLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panelContTextNombrejPanelLayout = new javax.swing.GroupLayout(panelContTextNombrejPanel);
        panelContTextNombrejPanel.setLayout(panelContTextNombrejPanelLayout);
        panelContTextNombrejPanelLayout.setHorizontalGroup(
            panelContTextNombrejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContTextNombrejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoNombreEstacionjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelContTextNombrejPanelLayout.setVerticalGroup(
            panelContTextNombrejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContTextNombrejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoNombreEstacionjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        getContentPane().add(panelContTextNombrejPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 360, 60));

        checkjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/check.png"))); // NOI18N
        checkjButton.setContentAreaFilled(false);
        checkjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkjButtonActionPerformed(evt);
            }
        });
        getContentPane().add(checkjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, 70, 70));

        pickColorjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/colorBlancoNegro.png"))); // NOI18N
        pickColorjButton.setContentAreaFilled(false);
        pickColorjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickColorjButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pickColorjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 85, 85));

        javax.swing.GroupLayout colorActualjPanelLayout = new javax.swing.GroupLayout(colorActualjPanel);
        colorActualjPanel.setLayout(colorActualjPanelLayout);
        colorActualjPanelLayout.setHorizontalGroup(
            colorActualjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        colorActualjPanelLayout.setVerticalGroup(
            colorActualjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(colorActualjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 80, 80));

        fondoPropEstacionjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estacionesMonopoly.jpg"))); // NOI18N
        getContentPane().add(fondoPropEstacionjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkjButtonActionPerformed
        if (nombreEstacionjTextField.getText().isEmpty() || colorEstacion==null) {
            crearTablero.mensajeError("Por favor, complete ambos campos");
        }
        else{
            String nombreEstacion = nombreEstacionjTextField.getText().trim();
            Color color = colorActualjPanel.getBackground();
            
            Estacion nuevaEstacion = new Estacion(fila, columna,nombreEstacion,
                    costoPorEstacion, porcentajeHipoteca , usoEstacion, color);
            
            setEstacion(nuevaEstacion);
            setColorEstacion(color);
            
            this.setVisible(false);     
        }
    }//GEN-LAST:event_checkjButtonActionPerformed

    public Color getColorEstacion() {
        return colorEstacion;
    }

    public void setColorEstacion(Color colorEstacion) {
        this.colorEstacion = colorEstacion;
    }

    public Estacion getEstacion() {
        return estacion;
    }

    public void setEstacion(Estacion estacion) {
        this.estacion = estacion;
    }

    private void pickColorjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickColorjButtonActionPerformed
        do {
            colorEstacion = JColorChooser.showDialog(this, "Elegir color de fondo", null);
        } while (colorEstacion == null);
        
        colorActualjPanel.setBackground(colorEstacion);
    }//GEN-LAST:event_pickColorjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkjButton;
    private javax.swing.JPanel colorActualjPanel;
    private javax.swing.JLabel fondoPropEstacionjLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nombreEstacionjTextField;
    private javax.swing.JPanel panelContTextColorEstacionjPanel;
    private javax.swing.JPanel panelContTextNombrejPanel;
    private javax.swing.JButton pickColorjButton;
    private javax.swing.JLabel textoNombreEstacionjLabel;
    private javax.swing.JLabel textoPropiedadesEstacionjLabel;
    // End of variables declaration//GEN-END:variables
}
