/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diseño;

import AdministradorGrupos.*;
import Casillas.Lugar;
import Casillas.ServicioBasico;
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author joel
 */
public class InstanciaServicioBasico extends javax.swing.JDialog {

    private CrearTablero crearTablero;
    private ManejadorPropiedades manejadorPropiedades;
    private GrupoLugar[] grupoL;
    private ServicioBasico servicioBasico;
    private Color colorServicio = null;
    private int fila;
    private int columna;
    private int porcentajeHipoteca;
    private String nombreServicio;
    

    public InstanciaServicioBasico(CrearTablero crearTablero, boolean modal,int fila, int columna, int porcentajeHipoteca) {
        super(crearTablero, modal);   
        initComponents();
        this.crearTablero = crearTablero;
        this.fila = fila;
        this.columna = columna;
        this.porcentajeHipoteca = porcentajeHipoteca;
           
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoPropiedadesjLabel = new javax.swing.JLabel();
        nombreServiciojTextField = new javax.swing.JTextField();
        aceptarjButton = new javax.swing.JButton();
        textoPrecioComprajLabel = new javax.swing.JLabel();
        textoColorjLabel = new javax.swing.JLabel();
        precioComprajSpinner = new javax.swing.JSpinner();
        costoUsoServiciojSpinner = new javax.swing.JSpinner();
        textoCostoUsoServiciojLabel = new javax.swing.JLabel();
        seletColorServiciojButton = new javax.swing.JButton();
        colorSeleccionadoServiciojPanel = new javax.swing.JPanel();
        textoNombreServiciojLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(870, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(770, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoPropiedadesjLabel.setBackground(new java.awt.Color(204, 204, 255));
        textoPropiedadesjLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 40)); // NOI18N
        textoPropiedadesjLabel.setForeground(new java.awt.Color(0, 51, 51));
        textoPropiedadesjLabel.setText("Atributos de Servicio Basico");
        textoPropiedadesjLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));
        getContentPane().add(textoPropiedadesjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 590, 50));

        nombreServiciojTextField.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nombreServiciojTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreServiciojTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nombreServiciojTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 270, 50));

        aceptarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/complete.png"))); // NOI18N
        aceptarjButton.setContentAreaFilled(false);
        aceptarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarjButtonActionPerformed(evt);
            }
        });
        getContentPane().add(aceptarjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, 110, 110));

        textoPrecioComprajLabel.setBackground(new java.awt.Color(255, 255, 255));
        textoPrecioComprajLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        textoPrecioComprajLabel.setForeground(new java.awt.Color(0, 0, 0));
        textoPrecioComprajLabel.setText("Precio Compra");
        textoPrecioComprajLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(textoPrecioComprajLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 220, 40));

        textoColorjLabel.setBackground(new java.awt.Color(255, 255, 255));
        textoColorjLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        textoColorjLabel.setForeground(new java.awt.Color(0, 0, 0));
        textoColorjLabel.setText("Color");
        textoColorjLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(textoColorjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 80, 40));

        precioComprajSpinner.setFont(new java.awt.Font("Capture it", 1, 24)); // NOI18N
        precioComprajSpinner.setModel(new javax.swing.SpinnerNumberModel(150, 1, null, 25));
        getContentPane().add(precioComprajSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 100, 40));

        costoUsoServiciojSpinner.setFont(new java.awt.Font("Capture it", 1, 24)); // NOI18N
        costoUsoServiciojSpinner.setModel(new javax.swing.SpinnerNumberModel(20, 1, null, 10));
        getContentPane().add(costoUsoServiciojSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 100, 40));

        textoCostoUsoServiciojLabel.setBackground(new java.awt.Color(255, 255, 255));
        textoCostoUsoServiciojLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        textoCostoUsoServiciojLabel.setForeground(new java.awt.Color(0, 0, 0));
        textoCostoUsoServiciojLabel.setText("Costo Uso Servicio");
        textoCostoUsoServiciojLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(textoCostoUsoServiciojLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 280, 40));

        seletColorServiciojButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/paleta-de-color.png"))); // NOI18N
        seletColorServiciojButton.setText("jButton1");
        seletColorServiciojButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        seletColorServiciojButton.setContentAreaFilled(false);
        seletColorServiciojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seletColorServiciojButtonActionPerformed(evt);
            }
        });
        getContentPane().add(seletColorServiciojButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 100, 90));

        colorSeleccionadoServiciojPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(colorSeleccionadoServiciojPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 140, 50));

        textoNombreServiciojLabel.setBackground(new java.awt.Color(255, 255, 255));
        textoNombreServiciojLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        textoNombreServiciojLabel.setForeground(new java.awt.Color(0, 0, 0));
        textoNombreServiciojLabel.setText("Nombre Servicio");
        textoNombreServiciojLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(textoNombreServiciojLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 280, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AguaCompany.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarjButtonActionPerformed
        if (nombreServiciojTextField.getText().isEmpty() || colorServicio==null) {
            crearTablero.mensajeError("Por favor ingrese todos los campos requeridos");
        }
        else{
            String nombreServicio = nombreServiciojTextField.getText().trim();
            int precioCompra = (Integer) precioComprajSpinner.getValue();
            int costoUsoServicio = (Integer) costoUsoServiciojSpinner.getValue();
            Color color = colorSeleccionadoServiciojPanel.getBackground();
            
            ServicioBasico nuevoServicio = new ServicioBasico(fila, columna, nombreServicio, precioCompra,
                    porcentajeHipoteca, costoUsoServicio, color);
            
            setServicioBasico(nuevoServicio);
            setColorServicio(color);
            setNombreServicio(nombreServicio);
            
            this.setVisible(false);
            
        }
        
    }//GEN-LAST:event_aceptarjButtonActionPerformed

    public ServicioBasico getServicioBasico() {
        return servicioBasico;
    }

    public void setServicioBasico(ServicioBasico servicioBasico) {
        this.servicioBasico = servicioBasico;
    }

    public Color getColorServicio() {
        return colorServicio;
    }

    public void setColorServicio(Color colorServicio) {
        this.colorServicio = colorServicio;
    }

    public String getNombreServicio() {
        return nombreServicio;
    }

    public void setNombreServicio(String nombreServicio) {
        this.nombreServicio = nombreServicio;
    }
    

    
    
    private void nombreServiciojTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreServiciojTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreServiciojTextFieldActionPerformed

    private void seletColorServiciojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seletColorServiciojButtonActionPerformed

        do {
            colorServicio = JColorChooser.showDialog(this, "Elegir color de fondo", null);
        } while (colorServicio == null);
        
        colorSeleccionadoServiciojPanel.setBackground(colorServicio);
    }//GEN-LAST:event_seletColorServiciojButtonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarjButton;
    private javax.swing.JPanel colorSeleccionadoServiciojPanel;
    private javax.swing.JSpinner costoUsoServiciojSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nombreServiciojTextField;
    private javax.swing.JSpinner precioComprajSpinner;
    private javax.swing.JButton seletColorServiciojButton;
    private javax.swing.JLabel textoColorjLabel;
    private javax.swing.JLabel textoCostoUsoServiciojLabel;
    private javax.swing.JLabel textoNombreServiciojLabel;
    private javax.swing.JLabel textoPrecioComprajLabel;
    private javax.swing.JLabel textoPropiedadesjLabel;
    // End of variables declaration//GEN-END:variables
}
