/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diseño;

import AdministradorGrupos.*;
import java.awt.Color;
import java.io.Serializable;

/**
 *
 * @author joel
 */
public class NumeroTarjetasTomeTarjeta extends javax.swing.JDialog implements Serializable{

    private EditarTarjetas editar;
    private CrearTablero crearTablero;
    private AdministradorGruposTomeTarjeta manejadorGrupos;
    private GrupoTarjeta[] gruposTarjeta;
    private Color[] coloresGrupo;
    private String[] nombresGrupo;
    private int[] numeroTarjetas;
    

    public NumeroTarjetasTomeTarjeta(EditarTarjetas editar,boolean modal, int[] numeroTarjetas,
            AdministradorGruposTomeTarjeta manejadorGrupos, CrearTablero crearTablero) {
        super(editar, modal);
        initComponents();
        this.editar = editar;
        this.crearTablero = crearTablero;
        this.manejadorGrupos = manejadorGrupos;
        this.numeroTarjetas = numeroTarjetas;

        establecer();
    }
    
    public void establecer(){

        nombresGrupo = manejadorGrupos.getNombresGrupos();
        coloresGrupo = manejadorGrupos.getColorGrupos();
        gruposTarjeta = manejadorGrupos.getGruposTarjeta();
        
        grupoTarjetajComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(nombresGrupo));
        colorGrupoActualjPanel.setBackground(coloresGrupo[grupoTarjetajComboBox.getSelectedIndex()]);
        
        if (numeroTarjetas!=null) {
            numeroElegidojTextField.setText(Integer.toString(numeroTarjetas[grupoTarjetajComboBox.getSelectedIndex()]));
        }
        
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTarjetajComboBox = new javax.swing.JComboBox<>();
        aceptarjButton = new javax.swing.JButton();
        textoElegirGrupojLabel = new javax.swing.JLabel();
        numeroTarjetasjSpinner = new javax.swing.JSpinner();
        colorGrupoActualjPanel = new javax.swing.JPanel();
        OKjButton = new javax.swing.JButton();
        numeroElegidojTextField = new javax.swing.JTextField();
        contenedorTextoNumeroTarjetasjPanel = new javax.swing.JPanel();
        textoNumerodeTarjetasjLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusable(false);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(640, 430));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grupoTarjetajComboBox.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        grupoTarjetajComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                grupoTarjetajComboBoxItemStateChanged(evt);
            }
        });
        grupoTarjetajComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupoTarjetajComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(grupoTarjetajComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 310, 40));

        aceptarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/complete.png"))); // NOI18N
        aceptarjButton.setContentAreaFilled(false);
        aceptarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarjButtonActionPerformed(evt);
            }
        });
        getContentPane().add(aceptarjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 80, 80));

        textoElegirGrupojLabel.setBackground(new java.awt.Color(255, 255, 255));
        textoElegirGrupojLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        textoElegirGrupojLabel.setForeground(new java.awt.Color(0, 102, 0));
        textoElegirGrupojLabel.setText("Elegir Grupo");
        textoElegirGrupojLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 0, 0), null, null));
        getContentPane().add(textoElegirGrupojLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 150, 40));

        numeroTarjetasjSpinner.setFont(new java.awt.Font("Capture it", 1, 36)); // NOI18N
        numeroTarjetasjSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(numeroTarjetasjSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 70, 50));

        colorGrupoActualjPanel.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(colorGrupoActualjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 310, 40));

        OKjButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        OKjButton.setText("OK");
        OKjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKjButtonActionPerformed(evt);
            }
        });
        getContentPane().add(OKjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, 50));

        numeroElegidojTextField.setEditable(false);
        numeroElegidojTextField.setBackground(new java.awt.Color(255, 255, 255));
        numeroElegidojTextField.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        numeroElegidojTextField.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(numeroElegidojTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 60, 50));

        contenedorTextoNumeroTarjetasjPanel.setBackground(new java.awt.Color(255, 255, 255));

        textoNumerodeTarjetasjLabel.setBackground(new java.awt.Color(255, 255, 255));
        textoNumerodeTarjetasjLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        textoNumerodeTarjetasjLabel.setForeground(new java.awt.Color(0, 0, 102));
        textoNumerodeTarjetasjLabel.setText("Numero de Tarjetas");
        textoNumerodeTarjetasjLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        contenedorTextoNumeroTarjetasjPanel.add(textoNumerodeTarjetasjLabel);

        getContentPane().add(contenedorTextoNumeroTarjetasjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 370, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/monopoly_board.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Devuelve el arreglo con los numeros de tarjetas que se quieren crear
 * @param evt 
 */
    private void aceptarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarjButtonActionPerformed
        if (arregloNumerosLleno()) { 
            editar.setCantidadTarjetas(numeroTarjetas);
            this.setVisible(false);
        }
        else{
            crearTablero.mensajeError("Faltan espacios por llenar");
        }
    }//GEN-LAST:event_aceptarjButtonActionPerformed

    private boolean arregloNumerosLleno(){
        for (int i = 0; i < numeroTarjetas.length; i++) {
            if (numeroTarjetas[i] == 0) {
                return false;
            }
        }
        return true;
    }
    
    
    private void grupoTarjetajComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_grupoTarjetajComboBoxItemStateChanged
        colorGrupoActualjPanel.setBackground(coloresGrupo[grupoTarjetajComboBox.getSelectedIndex()]);
        numeroElegidojTextField.setText(Integer.toString(numeroTarjetas[grupoTarjetajComboBox.getSelectedIndex()]));
    }//GEN-LAST:event_grupoTarjetajComboBoxItemStateChanged

    private void grupoTarjetajComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupoTarjetajComboBoxActionPerformed
        colorGrupoActualjPanel.setBackground(coloresGrupo[grupoTarjetajComboBox.getSelectedIndex()]);
    }//GEN-LAST:event_grupoTarjetajComboBoxActionPerformed

    private void OKjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKjButtonActionPerformed
        
        int eleccion = (Integer) numeroTarjetasjSpinner.getValue();      
        numeroTarjetas[grupoTarjetajComboBox.getSelectedIndex()] = eleccion;
        
        numeroElegidojTextField.setText(Integer.toString(eleccion));
        
    }//GEN-LAST:event_OKjButtonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKjButton;
    private javax.swing.JButton aceptarjButton;
    private javax.swing.JPanel colorGrupoActualjPanel;
    private javax.swing.JPanel contenedorTextoNumeroTarjetasjPanel;
    private javax.swing.JComboBox<String> grupoTarjetajComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField numeroElegidojTextField;
    private javax.swing.JSpinner numeroTarjetasjSpinner;
    private javax.swing.JLabel textoElegirGrupojLabel;
    private javax.swing.JLabel textoNumerodeTarjetasjLabel;
    // End of variables declaration//GEN-END:variables
}
