/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diseño;

import java.io.Serializable;

/**
 *
 * @author joel
 */
public class PrecioSalirCarcel extends javax.swing.JDialog implements Serializable {

    private int cantidadDinero;
    CrearTablero crearTablero;
    /**
     * Creates new form PrecioCarcel
     * @param crearTablero
     * @param modal
     */
    public PrecioSalirCarcel(CrearTablero crearTablero, boolean modal) {
        super(crearTablero, modal);
        initComponents();
        this.crearTablero = crearTablero;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerTextoPreciojPanel = new javax.swing.JPanel();
        textoPrecioSalirCarceljLabel = new javax.swing.JLabel();
        precioSalirCarceljSpinner = new javax.swing.JSpinner();
        aceptarjButton = new javax.swing.JButton();
        textoQjLabel = new javax.swing.JLabel();
        fondoPreciojLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusable(false);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        containerTextoPreciojPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoPrecioSalirCarceljLabel.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        textoPrecioSalirCarceljLabel.setForeground(new java.awt.Color(0, 0, 0));
        textoPrecioSalirCarceljLabel.setText("Precio para salir de carcel");
        containerTextoPreciojPanel.add(textoPrecioSalirCarceljLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 100));

        getContentPane().add(containerTextoPreciojPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 380, 100));

        precioSalirCarceljSpinner.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        precioSalirCarceljSpinner.setModel(new javax.swing.SpinnerNumberModel(50, 1, null, 10));
        getContentPane().add(precioSalirCarceljSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 80, 50));

        aceptarjButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        aceptarjButton.setText("Aceptar");
        aceptarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarjButtonActionPerformed(evt);
            }
        });
        getContentPane().add(aceptarjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 130, 50));

        textoQjLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        textoQjLabel.setText("Q");
        getContentPane().add(textoQjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 30, 50));

        fondoPreciojLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Carcel.jpg"))); // NOI18N
        getContentPane().add(fondoPreciojLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 398, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarjButtonActionPerformed
        cantidadDinero = (Integer)precioSalirCarceljSpinner.getValue();
        crearTablero.setPrecioSalirCarcel(cantidadDinero);
        this.setVisible(false);
    }//GEN-LAST:event_aceptarjButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarjButton;
    private javax.swing.JPanel containerTextoPreciojPanel;
    private javax.swing.JLabel fondoPreciojLabel;
    private javax.swing.JSpinner precioSalirCarceljSpinner;
    private javax.swing.JLabel textoPrecioSalirCarceljLabel;
    private javax.swing.JLabel textoQjLabel;
    // End of variables declaration//GEN-END:variables
}
