/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diseño;

import Casillas.Casilla;
import PilasYColas.ListaDECircular;
import java.awt.Color;
import java.awt.Dimension;
import java.io.Serializable;
import javax.swing.JPanel;

/**
 *
 * @author joel
 */
public class VistaPreviaTablero extends javax.swing.JDialog implements Serializable {

    private CrearJuego crearJuego;
    private ListaDECircular<Casilla> recorrido;
    private Casilla[][] tablero;
    private JPanel [][] casillas;
    private int filas;
    private int columnas;
    /**
     * Creates new form VistaPreviaTablero
     * @param crearJuego
     * @param modal
     * @param recorrido
     * @param tablero
     * @param filas
     * @param columnas
     */
    public VistaPreviaTablero(CrearJuego crearJuego, boolean modal,
            ListaDECircular<Casilla> recorrido, Casilla[][] tablero, int filas, int columnas) {
        super(crearJuego, modal);
        initComponents();
        this.crearJuego = crearJuego;
        this.recorrido = recorrido;
        this.tablero = tablero;
        this.filas = filas;
        this.columnas = columnas;
        imprimirTablero();
    }
    
    public void imprimirTablero(){
        tablerojPanel.setLayout(null);
        
        casillas = new JPanel[filas][columnas];
        int x=1;
        int y=1;
        
        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {
                casillas[i][j] = new JPanel();
                casillas[i][j].setBackground(Color.blue);
                casillas[i][j].setBounds(x, y, 50, 75);
                
                tablerojPanel.add(casillas[i][j]);
                x+=52;
            }
            x=1;
            y+=77;
        }
        
        tablerojPanel.setPreferredSize(new Dimension(50*filas+50, 75*columnas+50));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerTablerojScrollPane = new javax.swing.JScrollPane();
        tablerojPanel = new javax.swing.JPanel();
        containerComponentsjPanel = new javax.swing.JPanel();
        textoVistaPreviajLabel = new javax.swing.JLabel();
        ocultarjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout tablerojPanelLayout = new javax.swing.GroupLayout(tablerojPanel);
        tablerojPanel.setLayout(tablerojPanelLayout);
        tablerojPanelLayout.setHorizontalGroup(
            tablerojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );
        tablerojPanelLayout.setVerticalGroup(
            tablerojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );

        containerTablerojScrollPane.setViewportView(tablerojPanel);

        getContentPane().add(containerTablerojScrollPane, java.awt.BorderLayout.CENTER);

        textoVistaPreviajLabel.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        textoVistaPreviajLabel.setText("Vista Previa");

        ocultarjButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ocultarjButton.setText("Ocultar");
        ocultarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocultarjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerComponentsjPanelLayout = new javax.swing.GroupLayout(containerComponentsjPanel);
        containerComponentsjPanel.setLayout(containerComponentsjPanelLayout);
        containerComponentsjPanelLayout.setHorizontalGroup(
            containerComponentsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerComponentsjPanelLayout.createSequentialGroup()
                .addContainerGap(315, Short.MAX_VALUE)
                .addComponent(textoVistaPreviajLabel)
                .addGap(188, 188, 188)
                .addComponent(ocultarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        containerComponentsjPanelLayout.setVerticalGroup(
            containerComponentsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerComponentsjPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(containerComponentsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoVistaPreviajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ocultarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(containerComponentsjPanel, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ocultarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocultarjButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_ocultarjButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel containerComponentsjPanel;
    private javax.swing.JScrollPane containerTablerojScrollPane;
    private javax.swing.JButton ocultarjButton;
    private javax.swing.JPanel tablerojPanel;
    private javax.swing.JLabel textoVistaPreviajLabel;
    // End of variables declaration//GEN-END:variables
}
